[common]
recovery_retry_seconds = 5

[substrate]
chain = "polkadot"
chain_display = "Polkadot"
sidecar_url = "https://sidecar.helikon.io/polkadot"
connection_timeout_seconds = 15
request_timeout_seconds = 15
token_ticker = "DOT"
token_decimals = 10
token_format_decimal_points = 4

[log]
ftd_level = "debug"
other_level = "warn"

[postgres]
host = "127.0.0.1"
port = 5432
username = "ftd"
password = "ftd"
database_name = "ftd"
pool_max_connections = 64
connection_timeout_seconds = 5

[metrics]
host = "127.0.0.1"
indexer_port = 11000