[common]
recovery_retry_seconds = 5

[log]
ftd_level = "debug"
other_level = "warn"

[postgres]
host = "127.0.0.1"
port = 5432
username = "ftd"
password = "ftd"
database_name = "ftd"
pool_max_connections = 64
connection_timeout_seconds = 5

[neo4j]
host = "127.0.0.1"
port = 7687
username = "neo4j"
password = "neo4j_password"
database_name = "neo4j"

[substrate]
chain = "polkadot"
chain_display = "Polkadot"
rpc_url = "wss://rpc.helikon.io:443/polkadot"
people_rpc_url = "wss://rpc.helikon.io:443/people-polkadot"
sidecar_url = "https://sidecar.helikon.io/polkadot"
connection_timeout_seconds = 15
request_timeout_seconds = 15
token_ticker = "DOT"
token_decimals = 10
token_format_decimal_points = 4

[api]
request_timeout_seconds = 60
service_host = "0.0.0.0"
api_service_port = 7900
account_search_limit = 25
graph_search_limit = 100

[subscan]
api_key = "subscan_api_key"
account_data_url = "https://polkadot.api.subscan.io/api/v2/scan/search"
account_list_url = "https://polkadot.api.subscan.io/api/v2/scan/accounts"
sleep_seconds = 10

[indexer]
start_block_number = 12_000_000
# end_block_number = 12_000_500
chunk_size = 100

[identity_updater]
sleep_seconds = 10

[metrics]
host = "127.0.0.1"
indexer_port = 11010
transfer_volume_updater_port = 11011
identity_updater_port = 11012
graph_updater_port = 11013
subscan_account_fetcher_port = 11014
api_service_port = 11015