version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/ftd-backend'
    target-branch: 'development'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/ftd-web'
    target-branch: 'development'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'